### ISSUE TITLE
Add `is_empty()` to public API of all newtypes that have implemented `len()`

### ISSUE THREAD

**Issue by brycx** [orion-rs/orion#205]
Clippy now warns on

```
struct `Password` has a public `len` method, but no `is_empty` method
```

IIRC all newtypes either don't accept empty input or don't hold an empty inner value after creation (e.g the HMAC `SecretKey` accepts empty input, but pads the data so the actual `SecretKey` will always have some bytes in it). The question is, if all newtypes are `is_empty() == false`, should we even add the `is_empty()` method?

Following clippy guidelines in general seems like a good idea. If we're going to add it, I think it should be added to all newtypes,, regardless of what behavior we expect from them. Maybe we also end up adding newtypes in the future, that actually can be empty, and in that case it makes sense to have it. Apart from additional testing, I see no big drawbacks and therefor think we might as well add it.

Thoughts @vlmutolo?

**Comment by vlmutolo** [comment]
This is a pretty interesting question. This lint always gives me pause. For me, the answer is about whether `is_empty` is meaningful for the given type, and not so much about whether the function can ever return `true`. A simple line in the docs for that method explaining that it's always `false` should do it. 

Here, it seems like we're talking about Passwords and Keys of various types—basically, newtypes over simple byte strings. It seems to me that if String can be "empty" in the sense that we model it as a byte container with extra restrictions, then Password and SecretKey and Digest should have `is_empty` by similar logic.

**Comment by brycx** [comment]
> It seems to me that if String can be "empty" in the sense that we model it as a byte container with extra restrictions, then Password and SecretKey and Digest should have is_empty by similar logic.

This is the tricky part. We have no newtypes of that sort that can be empty. Once they've been created with `from`/`from_slice`, they're never empty. Not even the high-level types. But it might also happen we add them in the future.

> For me, the answer is about whether is_empty is meaningful for the given type, and not so much about whether the function can ever return true.

I agree. I'm afraid `is_empty` would imply instead that the current newtypes actually __can__ be empty, when that's not the case.

**Comment by vlmutolo** [comment]
Do we have any specific types in mind that may be added in the future where `is_empty` may return `true`? If not, let's just work with what we have and document that the method will always return `false`. If that changes and some type may be empty, we can reevaluate how we want to document things. And yes, I can take on that documentation.

**Comment by brycx** [comment]
> Do we have any specific types in mind that may be added in the future where is_empty may return true?

No, none in particular.

> If not, let's just work with what we have and document that the method will always return false

Sounds like a good plan. We'll add `is_empty` to newtypes then.

> If that changes and some type may be empty, we can reevaluate how we want to document things. And yes, I can take on that documentation.

Awesome.
