### ISSUE TITLE
BLAKE2b return type with more protections

### ISSUE THREAD

**Issue by brycx** [orion-rs/orion#208]
While implementing a XChaCha20-BLAKE2b construct, as part of the PASETO v4 spec, I had to use BLAKE2b to [derive encryption and authentication keys](https://github.com/brycx/pasetors/blob/83a76eb96f6e4353cfc8270c7ca2646d2888d62e/src/version4.rs#L162). That meant dealing with the public/unprotected `Digest` newtype, holding sensitive bytes, but without the newtype having a zeroizing `Drop` implementation. Already, the `Digest` type is somewhat awkward in terms of BLAKE2b, since it's not like the `Tag` used by HMAC, that offers more protections and also results in the following documentation:

```
//! - When using Blake2b with a secret key, then the output can be used as a
//!   MAC. If this is the intention, __**avoid using**__ [`as_ref()`]
//!   to compare such MACs and use instead [`verify()`], which will compare
//!   the MAC in constant time.
``` 

Implementing the XChaCha20-BLAKE2b construct has lead me to think that the current protections offered by the return type of BLAKE2b are insufficient. So far, the following approach seems the most reasonable to me:

Add a `Drop` to the `Tag` newtypes and replace `Digest` with `Tag` in BLAKE2b. This, however, requires us to remove the auto-derive of the `Copy` trait in the `construct_tag` macro, meaning that all tag newtypes no longer implement `Copy`, only `Clone`. `Tag` seems to be the best-fitting newtype for BLAKE2b, as it's used with other MACs in Orion.

I don't see a big problem with removing `Copy` from tag, as long as `Clone` is still available. `Drop` could also be implemented for the `Digest` currently used in BLAKE2b, resulting in "less breaking" changes, but that also implies removing `Copy` for all other public newtypes.

In any case, it seems like a good idea to me, to change the return type of BLAKE2b. Sure, it can be used as a hash function only, but if it can also be used as MAC, should the return type then not represent the case where most protection is needed, to increase misuse-resistance? 

cc @vlmutolo

**Comment by vlmutolo** [comment]
The rationale makes sense to me. The only concern I'd have is that returning a Tag from blake might confused users expecting a Digest. I imagine that the majority of people using blake aren't using the keyed version. That said, though, I also imagine that most people looking for a hash would use the Orion::hash module. 

Could we have hazardous::blake return a Tag, but then have the hash module return a Digest?

**Comment by brycx** [comment]
> Could we have hazardous::blake return a Tag, but then have the hash module return a Digest?

I was actually thinking having `hazardous::hash::blake2b::Blake2b` return a `Tag`, but having the `Hasher` enum still return a `Digest`. And yes, keeping the `Digest` in the high-level interface as well.

**Comment by brycx** [comment]
After trying the above approach, I found that it made the implementation overly complicated, such as in terms of testing. It also seemed non-intuitive to have a module both return `Tag` and `Digest` in some cases, depending on whether an `Option<SecretKey>` had been used or not.

I've now tried another approach, similar to how the generalized SHA2 implementation was built. By having an internal core BLAKE2b state implementation, that is used by publicly exposed states. Public states in the `hazardous::mac` and `hazardous::hash` modules. So, then the API would be:

```
hazardous::hash::blake2b::Blake2b
    -> new(size)
    -> reset()
    -> update()
    -> finialize() -> Digest 
```

```
hazardous::mac::blake2b::Blake2b
    -> new(secret_key, size)
    -> reset(secret_key)
    -> update()
    -> finialize() -> Tag 
```

Note that now the secret key parameter doesn't need to be an `Option` either.


Another small drawback of the previous approach, was that it put a greater workload on our Argon2i implementation through an added zeroizing `Drop` implementation. Now, we can keep using `Digest` which should be a bit cheaper.

see the PR #209

**Comment by vlmutolo** [comment]
I really like this solution. I hadn't thought about exposing it once in mac and once in hash. This definitely fits well. 

I wonder if there's ever a scenario where someone would want a keyed cryptographic hash that isn't for a MAC. I can't really think of anything off the top of my head. If that ever comes up, though, I don't think it would be too difficult to re-expose the key parameter in the `hash` module.
