### ISSUE TITLE
Terminology "secret key" vs. "private key" in asymmetric crypto

### ISSUE THREAD

**Issue by brycx** [orion-rs/orion#217]
The PR for X25519 just got merged, but immediately after I realized that the terminology used currently ("secret key" & "public key") might not be the correct. I believe it's more common to associate "private key" and "public key" with asymmetric crypto, so "secret key" should probably be renamed to "private key".

Perhaps even "SharedSecret" to "SharedKey".

cc @vlmutolo

**Comment by vlmutolo** [comment]
Yes, I'd have to agree with this. When I see "secret key", I definitely think of symmetric, shared-key crypto. "Private key" would be a lot clearer.

**Comment by brycx** [comment]
> In hindsight, I should have taken some more time to at least look through the generated documentation and give an outsider's perspective. (Outsider in the sense that I didn't write that code or documentation.) I'll do that in the future.

This is great to do. But this is mostly my fault, since I didn't request a review for the X25519 `hazardous` review (I know you're not exactly made of time). I decided that, we were probably going to spend some reasonable time discussing and reviewing the high-level API for key-exchange with X25519, so this issue would've come up at that point anyway.
