### ISSUE TITLE
CI: Switching from `cargo-audit` to `actions-rs/audit-check`

### ISSUE THREAD

**Issue by brycx** [orion-rs/orion#257]
The README of `cargo-audit` mentions you should use `audit-check` directly, but it seems to me the repository isn't being updated currently. Last commit was March 2020 and several fixes pend review/merging for new releases. Let's keep an eye on this audit action for now.

A nice pro for switching to `audit-check` is it will open issues for any RustSec advisories.

https://github.com/RustSec/rustsec/tree/main/cargo-audit
https://github.com/actions-rs/audit-check

**Comment by brycx** [comment]
This is the underlying reason as to why issues are not opened as mentioned in #251

**Comment by vlmutolo** [comment]
> A nice pro for switching to audit-check is it will open issues for any RustSec advisories.

That's really cool.

**Comment by brycx** [comment]
> I assume it notifies based on what dependencies you have in your tree and their versions (?).

Precisely. Just the direct dependencies in our Cargo.toml file.
