### ISSUE TITLE
`nightly` doctest builds fail

### ISSUE THREAD

**Issue by brycx** [orion-rs/orion#275]
See latest daily test https://github.com/orion-rs/orion/runs/5133963839?check_suite_focus=true

**Comment by vlmutolo** [comment]
I can take a look tomorrow afternoon (5ish EST). Seems like it's the io trait impls. I wonder why it's suddenly failing.

**Comment by brycx** [comment]
Would be very helpful!

**Comment by vlmutolo** [comment]
Turns out this the issue was temporary. Current nightly builds pass.
