### ISSUE TITLE
`Digest` to `&[u8]`

### ISSUE THREAD

**Issue by Fraccaman** [orion-rs/orion#355]
Probably I'm overseeing this, but is there a way to get a `&[u8]` from a `Digest` ?

**Comment by brycx** [comment]
All `Digest`s should implement `AsRef<[u8]>`, so you should be able to get `&[u8]` through there: `digest.as_ref()`.

**Comment by brycx** [comment]
I'll close this for now. Feel free to re-open if there's any issue with this.
